---
- hosts: ultravps
  tasks:
  - name: copy file to srv
    copy: 
      src: ./monerod.service
      dest: /etc/systemd/system/monerod.service
      mode: '0644'
  - name: enable service monerod and ensure it is not masked
    systemd:
      name: monerod
      enabled: yes
      masked: no
  - name: Make sure a service is running
    systemd:
      state: started
      name: monerod


# default dirs for "service" file in systemd are: /etc/systemd/system or /lib/systemd/system