---
- hosts: ultravps
  tasks:
  - name: copy file to srv
    copy: 
      src: ./monero.service
      dest: /etc/systemd/system/monero.service
      mode: '0644'
  - name: enable service monero and ensure it is not masked
    systemd:
      name: monero
      enabled: yes
      masked: no
  - name: Make sure a service is running
    systemd:
      state: started
      name: monero


# default dirs for "service" file in systemd are: /etc/systemd/system or /lib/systemd/system
